# Generated by Django 3.0.7 on 2020-08-31 06:46

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200831_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_overview',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=' '),
            preserve_default=False,
        ),
    ]
