# Generated by Django 3.0.7 on 2020-06-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Address',
            field=models.CharField(default='Not Provided Yet', max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='desccription',
            field=models.CharField(default='Hi There I am Single yet ...... ', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='profession',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='whattsapp',
            field=models.CharField(default='Not Provided Yet', max_length=20),
        ),
    ]
