# Generated by Django 2.0.1 on 2020-06-15 07:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200608_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='desccription',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=100),
        ),
    ]
