# Generated by Django 2.0.1 on 2020-06-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200615_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='desccription',
            field=models.CharField(default='Hi There I am Single yet ...... ', max_length=100),
        ),
    ]
