# Generated by Django 2.0.1 on 2020-07-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200616_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Address',
            field=models.CharField(blank=True, default='Not Provided Yet', max_length=64),
        ),
        migrations.AlterField(
            model_name='profile',
            name='desccription',
            field=models.CharField(blank=True, default='Hi There I am Single yet ...... ', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profession',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='whattsapp',
            field=models.CharField(blank=True, default='Not Provided Yet', max_length=20),
        ),
    ]
